@extends('layouts.master')
@section('title')
    Personal
@endsection
@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            RRHH
        @endslot
        @slot('title')
            Personal
        @endslot
    @endcomponent
    @livewire('rrhh.personal.filtro')
    @livewire('rrhh.personal.table')
    @livewire('rrhh.personal.ver-detalles')
    @livewire('rrhh.personal.components.pre-grado')
    @livewire('rrhh.personal.components.post-grado')
    @livewire('rrhh.personal.components.colegiatura')
    @livewire('rrhh.personal.components.experiencia-laboral')
    @livewire('rrhh.personal.components.otros-estudios')
@endsection
