@extends('layouts.master')
@section('title')
    Escalafon
@endsection
@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            RRHH
        @endslot
        @slot('title')
            Escalafon
        @endslot
    @endcomponent
    @livewire('rrhh.personal.escalafon.filtro')
    @livewire('rrhh.personal.escalafon.table')
@endsection
