@extends('layouts.master')
@section('title')
    Caja
@endsection
@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Academico
        @endslot
        @slot('title')
            Caja
        @endslot
    @endcomponent
    @livewire('academico.caja.filtro')
    @livewire('academico.caja.resumen')
    @livewire('academico.caja.table')
    @livewire('academico.caja.ver-detalles')
@endsection
