@extends('layouts.master')
@section('title')
    Personal
@endsection
@section('css')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" type="text/css" />
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Qr
        @endslot
        @slot('title')
            Patrimonio
        @endslot
    @endcomponent
    @livewire('patrimonio.qr.base');
    @livewire('patrimonio.qr.buscar-eq');
    @livewire('patrimonio.qr.inventariar');
    @livewire('patrimonio.qr.buscar-number');
@endsection
