@extends('layouts.master')
@section('title')
    Personal
@endsection
@section('css')
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Qr
        @endslot
        @slot('title')
            Patrimonio
        @endslot
    @endcomponent
    @livewire('patrimonio.qr.base')
    @livewire('patrimonio.qr.buscar-eq')
    @livewire('patrimonio.qr.inventariar')
    @livewire('patrimonio.qr.buscar-number')
@endsection
