@extends('layouts.master')
@section('title')
    Compras
@endsection
@section('css')
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Compras
        @endslot
        @slot('title')
            Compras
        @endslot
    @endcomponent
    @livewire('financiero-contable.compras.compras.filtro')
    @livewire('financiero-contable.compras.compras.table')
    @livewire('financiero-contable.compras.compras.ver-detalles')
    @livewire('financiero-contable.compras.compras.components.ver-recurso')
    @livewire('financiero-contable.compras.compras.editar-item')
@endsection
