@extends('layouts.master')
@section('title')
    Inicio
@endsection
@section('css')
   
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Biblioteca
        @endslot
        @slot('title')
            Inicio
        @endslot
    @endcomponent
    @livewire('biblioteca.cards')
@endsection
@section('script')
@endsection
