@extends('layouts.master')
@section('title')
    Libros
@endsection
@section('css')
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Biblioteca
        @endslot
        @slot('title')
            Libros
        @endslot
    @endcomponent
    @livewire('biblioteca.libros.filtro')
    @livewire('biblioteca.libros.table')
    @livewire('biblioteca.libros.components.devolver')
    @livewire('biblioteca.libros.components.ver-mas')
@endsection
